apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: owasso-covid
build:
  artifacts:
  - image: seppler/owasso-covid-nginx
    docker:
      dockerfile: Dockerfile-frontend
  - image: seppler/owasso_covid
deploy:
  kubectl:
    manifests:
    - k8s/cronjob.yaml
    - k8s/frontend.yaml
    - k8s/ingress.yaml
    - k8s/pv.yaml
    - k8s/pvc.yaml
    - k8s/service.yaml
