apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: generate-graphs
  namespace: owasso-covid
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: generate-graphs
            image: seppler/owasso_covid-update_db:2.0.2
            volumeMounts:
            - name: db
              mountPath: /db
          restartPolicy: OnFailure
          volumes:
          - name: db
            persistentVolumeClaim:
              claimName: owasso-covid-db