apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: vault-issuer
    traefik.frontend.rule.type: PathPrefixStrip
  name: owasso-covid
  namespace: owasso-covid
spec:
  rules:
  - host: codaubuntu
    http:
      paths:
      - backend:
          serviceName: owasso-covid
          servicePort: 3001
        path: /owasso-covid
  - host: audioboxer.onthewifi.com
    http:
      paths:
      - backend:
          serviceName: owasso-covid
          servicePort: 3001
        path: /owasso-covid
  tls:
  - hosts:
    - audioboxer.onthewifi.com
    secretName: ingress-cert
