apiVersion: v1
kind: PersistentVolume
metadata:
  name: owasso-covid-db
  labels:
    app: owasso-covid
    use: db
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /media/owasso_covid/db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: owasso-covid-graphs
  labels:
    app: owasso-covid
    use: output
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /media/owasso_covid/graphs
