apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owasso-covid-db
  namespace: owasso-covid
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: local
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: owasso-covid
      use: db
